navigation:
  - title : "Home"
    url   : "/index.html"
  - title : "Schedule"
    url   : "/schedule/index.html"
  - title : "Topics"
    url   : "/topics/index.html"
  - title : "Speakers"
    url   : "/speakers/index.html"
  - title : "Venue"
    url   : "/venue/index.html"
  - title : "Sponsors"
    url   : "/sponsors/index.html"
  - title : "Past"
    url   : "/past/index.html"
  - title : "Register"
    url   : "/register/index.html"
