navigation:
  - title : "Home"
    url   : "/index.html"
  - title : "Speakers"
    url   : "/speakers/index.html"
  - title : "Topics"
    url   : "/topics/index.html"
  - title : "Registration"
    url   : "https://registration.turkuagileday.fi/"
  - title : "Venue"
    url   : "/venue/index.html"
  - title : "Past"
    url   : "/past/index.html"