navigation:
  - title : "Home"
    url   : "/index.html"
  - title : "Speakers"
    url   : "/speakers/index.html"
  - title : "Topics"
    url   : "/topics/index.html"
  - title : "Past"
    url   : "/past/index.html"
