navigation:
  - title : "Home"
    url   : "/index.html"
  - title : "Sponsors"
    url   : "/sponsors/index.html"
  - title : "Schedule"
    url   : "/schedule/index.html"
  - title : "Speakers"
    url   : "/speakers/index.html"
  - title : "Topics"
    url   : "/topics/index.html" 
  - title : "Registration"
    url   : "https://registration.turkuagileday.fi/"
  - title : "Venue"
    url   : "/venue/index.html"
  - title : "Past"
    url   : "/past/index.html"
#  - title : "Call for proposals"
#   url   : "/proposals/index.html"
